version: '3'
services:
  node1:
    build: .
    ports:
      - "8080:8080"
  node2:
    build: .
    ports:
      - "8081:8080"
  management:
    image: hazelcast/management-center
    ports:
      - "8082:8080"
