version: '3'
services:
  lb:
    build: nginx
    ports:
      - 8080:8080
  node1:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - ./tmp:/tmp
  node2:
    build: .
    ports:
      - "8082:8080"
    volumes:
      - ./tmp:/tmp
  management:
    image: hazelcast/management-center
    ports:
      - "8083:8080"
